### PR TITLE
Update nalgebra to 0.27.1

### PR DESCRIPTION
**Pull request by mpizenberg**
And transform all that needed to change with the nalgebra update. In particular:
- `MatrixMN` => `OMatrix`
- `VectorN` => `OVector`
- `..._generic_...(U1)` => `let u1 = Dim::from_usize(1); ..._generic_...(u1)`

Currently there is one test that is failing. I think this is a `relative_eq` versus `eq` problem but I'll let you check that.

Also will need to change de dependency `"../arrsac"` to the actual `arrsac` when it's updated so I made this PR a draft one for now.

### CODE REVIEW

**Comment by mpizenberg** [comment]
Actually, it might be worth changing the `OMatrix` and `OVector` where sizes are const to `SMatrix` and `SVector`.

**Comment by mpizenberg** [comment]
The failing lints seems to be related to nightly usage in CI. When using stable, all seems fine, should we change the lints CI to compile on stable?

**Comment by mpizenberg** [comment]
Also, `cargo test` seems to be fine, but if I run `cargo test --all-features` on my machine, one test is failing. What should we do about that?

**Comment by vadixidav** [comment]
It is preferable for lints to be nightly so that we get a warning ahead of breaking changes in the language that can occasionally happen when there is a security risk (very rare). I will take a look at the lints and see if we can just fix those in the code. If not, we can just merge it with those lints failing if they are nightly-only.

**Comment by vadixidav** [comment]
> 
> 
> Also, `cargo test` seems to be fine, but if I run `cargo test --all-features` on my machine, one test is failing. What should we do about that?

This is a problem that I don't know how to solve. The minpack-compat feature enables a test that only works on one particular machine configuration because the way minpack works is specific to each machine. This is unfortunate for our testing, but currently an issue. I think we should just deal with this for now because it is good to have the test there, even though it may only work on one machine. Running the tests without minpack-compat feature is sufficient.

**Pull request merged**
